/**
 * FIFA World Cup 2026 「ベスト3位通過」割当ロジック（純TS・DB非依存）。
 *
 * 48チーム制では 12 グループ各3位の計12チームのうち、上位8チームが Round of 32 に進む。
 * 「どの3位がどの試合（＝どのグループ1位の相手）に入るか」は抽選ではなく、通過した8グループ
 * の組合せごとに FIFA が事前確定している（公式 Competition Regulations Annex C）。
 *
 * 本モジュールはその全 495 通り (= C(12,8)) のルックアップ表を正典どおり保持し、
 * 「通過した8グループ → 各ホスト試合に入る3位グループ」を引く純関数を提供する。
 *
 * 出典・生成: scripts/gen-third-place-table.ts が Wikipedia の
 *   Template:2026_FIFA_World_Cup_third-place_table（FIFA Annex C の転記）の生 wikitext を
 *   パースして本表を生成する。手書き転記はしていない（495行のヒューマンエラー排除）。
 *   生成時に「全網羅・割当先=通過集合・自グループ回避」の不変条件を検証済み。
 */

/** グループ識別子 A〜L。 */
export type GroupLetter =
  | 'A' | 'B' | 'C' | 'D' | 'E' | 'F'
  | 'G' | 'H' | 'I' | 'J' | 'K' | 'L';

/**
 * 3位通過チームを受け入れる Round of 32 の8試合（試合ID）と、その「ホスト」＝対戦するグループ1位。
 *
 * 例: 試合74 は「グループE 1位 vs ベスト3位のいずれか」。ホスト文字 'E' で表に問い合わせる。
 * seed-matches.ts の id / homeSlot と一致（変更不可の FIFA 公式スケジュール由来）。
 */
export const THIRD_PLACE_HOST_MATCHES: { matchId: number; host: GroupLetter }[] = [
  { matchId: 74, host: 'E' },
  { matchId: 77, host: 'I' },
  { matchId: 79, host: 'A' },
  { matchId: 80, host: 'L' },
  { matchId: 81, host: 'D' },
  { matchId: 82, host: 'G' },
  { matchId: 85, host: 'B' },
  { matchId: 87, host: 'K' },
];

/**
 * ルックアップ表のホスト列順。`THIRD_PLACE_ALLOCATIONS` の各エントリ2要素目（割当8文字）は
 * この順で「そのホスト1位の相手になる3位グループ」を表す。
 * （wikitext ヘッダ "1A vs / 1B vs / 1D vs / 1E vs / 1G vs / 1I vs / 1K vs / 1L vs" と一致。）
 */
export const ALLOCATION_HOST_ORDER: readonly GroupLetter[] = [
  'A', 'B', 'D', 'E', 'G', 'I', 'K', 'L',
] as const;

/**
 * 全 495 通りの割当表。各エントリは [通過した8グループ(昇順), ホスト順の割当3位グループ8文字]。
 *
 * 例: ['EFGHIJKL', 'EJIFHGLK']
 *   → 通過 = E,F,G,H,I,J,K,L
 *   → 1A=3E, 1B=3J, 1D=3I, 1E=3F, 1G=3H, 1I=3G, 1K=3L, 1L=3K（ALLOCATION_HOST_ORDER 順）
 *
 * 生成元: scripts/gen-third-place-table.ts（出典は同ファイル冒頭参照）。
 */
export const THIRD_PLACE_ALLOCATIONS: readonly (readonly [string, string])[] = [
  ['EFGHIJKL', 'EJIFHGLK'],
  ['DFGHIJKL', 'HGIDJFLK'],
  ['DEGHIJKL', 'EJIDHGLK'],
  ['DEFHIJKL', 'EJIDHFLK'],
  ['DEFGIJKL', 'EGIDJFLK'],
  ['DEFGHJKL', 'EGJDHFLK'],
  ['DEFGHIKL', 'EGIDHFLK'],
  ['DEFGHIJL', 'EGJDHFLI'],
  ['DEFGHIJK', 'EGJDHFIK'],
  ['CFGHIJKL', 'HGICJFLK'],
  ['CEGHIJKL', 'EJICHGLK'],
  ['CEFHIJKL', 'EJICHFLK'],
  ['CEFGIJKL', 'EGICJFLK'],
  ['CEFGHJKL', 'EGJCHFLK'],
  ['CEFGHIKL', 'EGICHFLK'],
  ['CEFGHIJL', 'EGJCHFLI'],
  ['CEFGHIJK', 'EGJCHFIK'],
  ['CDGHIJKL', 'HGICJDLK'],
  ['CDFHIJKL', 'CJIDHFLK'],
  ['CDFGIJKL', 'CGIDJFLK'],
  ['CDFGHJKL', 'CGJDHFLK'],
  ['CDFGHIKL', 'CGIDHFLK'],
  ['CDFGHIJL', 'CGJDHFLI'],
  ['CDFGHIJK', 'CGJDHFIK'],
  ['CDEHIJKL', 'EJICHDLK'],
  ['CDEGIJKL', 'EGICJDLK'],
  ['CDEGHJKL', 'EGJCHDLK'],
  ['CDEGHIKL', 'EGICHDLK'],
  ['CDEGHIJL', 'EGJCHDLI'],
  ['CDEGHIJK', 'EGJCHDIK'],
  ['CDEFIJKL', 'CJEDIFLK'],
  ['CDEFHJKL', 'CJEDHFLK'],
  ['CDEFHIKL', 'CEIDHFLK'],
  ['CDEFHIJL', 'CJEDHFLI'],
  ['CDEFHIJK', 'CJEDHFIK'],
  ['CDEFGJKL', 'CGEDJFLK'],
  ['CDEFGIKL', 'CGEDIFLK'],
  ['CDEFGIJL', 'CGEDJFLI'],
  ['CDEFGIJK', 'CGEDJFIK'],
  ['CDEFGHKL', 'CGEDHFLK'],
  ['CDEFGHJL', 'CGJDHFLE'],
  ['CDEFGHJK', 'CGJDHFEK'],
  ['CDEFGHIL', 'CGEDHFLI'],
  ['CDEFGHIK', 'CGEDHFIK'],
  ['CDEFGHIJ', 'CGJDHFEI'],
  ['BFGHIJKL', 'HJBFIGLK'],
  ['BEGHIJKL', 'EJIBHGLK'],
  ['BEFHIJKL', 'EJBFIHLK'],
  ['BEFGIJKL', 'EJBFIGLK'],
  ['BEFGHJKL', 'EJBFHGLK'],
  ['BEFGHIKL', 'EGBFIHLK'],
  ['BEFGHIJL', 'EJBFHGLI'],
  ['BEFGHIJK', 'EJBFHGIK'],
  ['BDGHIJKL', 'HJBDIGLK'],
  ['BDFHIJKL', 'HJBDIFLK'],
  ['BDFGIJKL', 'IGBDJFLK'],
  ['BDFGHJKL', 'HGBDJFLK'],
  ['BDFGHIKL', 'HGBDIFLK'],
  ['BDFGHIJL', 'HGBDJFLI'],
  ['BDFGHIJK', 'HGBDJFIK'],
  ['BDEHIJKL', 'EJBDIHLK'],
  ['BDEGIJKL', 'EJBDIGLK'],
  ['BDEGHJKL', 'EJBDHGLK'],
  ['BDEGHIKL', 'EGBDIHLK'],
  ['BDEGHIJL', 'EJBDHGLI'],
  ['BDEGHIJK', 'EJBDHGIK'],
  ['BDEFIJKL', 'EJBDIFLK'],
  ['BDEFHJKL', 'EJBDHFLK'],
  ['BDEFHIKL', 'EIBDHFLK'],
  ['BDEFHIJL', 'EJBDHFLI'],
  ['BDEFHIJK', 'EJBDHFIK'],
  ['BDEFGJKL', 'EGBDJFLK'],
  ['BDEFGIKL', 'EGBDIFLK'],
  ['BDEFGIJL', 'EGBDJFLI'],
  ['BDEFGIJK', 'EGBDJFIK'],
  ['BDEFGHKL', 'EGBDHFLK'],
  ['BDEFGHJL', 'HGBDJFLE'],
  ['BDEFGHJK', 'HGBDJFEK'],
  ['BDEFGHIL', 'EGBDHFLI'],
  ['BDEFGHIK', 'EGBDHFIK'],
  ['BDEFGHIJ', 'HGBDJFEI'],
  ['BCGHIJKL', 'HJBCIGLK'],
  ['BCFHIJKL', 'HJBCIFLK'],
  ['BCFGIJKL', 'IGBCJFLK'],
  ['BCFGHJKL', 'HGBCJFLK'],
  ['BCFGHIKL', 'HGBCIFLK'],
  ['BCFGHIJL', 'HGBCJFLI'],
  ['BCFGHIJK', 'HGBCJFIK'],
  ['BCEHIJKL', 'EJBCIHLK'],
  ['BCEGIJKL', 'EJBCIGLK'],
  ['BCEGHJKL', 'EJBCHGLK'],
  ['BCEGHIKL', 'EGBCIHLK'],
  ['BCEGHIJL', 'EJBCHGLI'],
  ['BCEGHIJK', 'EJBCHGIK'],
  ['BCEFIJKL', 'EJBCIFLK'],
  ['BCEFHJKL', 'EJBCHFLK'],
  ['BCEFHIKL', 'EIBCHFLK'],
  ['BCEFHIJL', 'EJBCHFLI'],
  ['BCEFHIJK', 'EJBCHFIK'],
  ['BCEFGJKL', 'EGBCJFLK'],
  ['BCEFGIKL', 'EGBCIFLK'],
  ['BCEFGIJL', 'EGBCJFLI'],
  ['BCEFGIJK', 'EGBCJFIK'],
  ['BCEFGHKL', 'EGBCHFLK'],
  ['BCEFGHJL', 'HGBCJFLE'],
  ['BCEFGHJK', 'HGBCJFEK'],
  ['BCEFGHIL', 'EGBCHFLI'],
  ['BCEFGHIK', 'EGBCHFIK'],
  ['BCEFGHIJ', 'HGBCJFEI'],
  ['BCDHIJKL', 'HJBCIDLK'],
  ['BCDGIJKL', 'IGBCJDLK'],
  ['BCDGHJKL', 'HGBCJDLK'],
  ['BCDGHIKL', 'HGBCIDLK'],
  ['BCDGHIJL', 'HGBCJDLI'],
  ['BCDGHIJK', 'HGBCJDIK'],
  ['BCDFIJKL', 'CJBDIFLK'],
  ['BCDFHJKL', 'CJBDHFLK'],
  ['BCDFHIKL', 'CIBDHFLK'],
  ['BCDFHIJL', 'CJBDHFLI'],
  ['BCDFHIJK', 'CJBDHFIK'],
  ['BCDFGJKL', 'CGBDJFLK'],
  ['BCDFGIKL', 'CGBDIFLK'],
  ['BCDFGIJL', 'CGBDJFLI'],
  ['BCDFGIJK', 'CGBDJFIK'],
  ['BCDFGHKL', 'CGBDHFLK'],
  ['BCDFGHJL', 'CGBDHFLJ'],
  ['BCDFGHJK', 'HGBCJFDK'],
  ['BCDFGHIL', 'CGBDHFLI'],
  ['BCDFGHIK', 'CGBDHFIK'],
  ['BCDFGHIJ', 'HGBCJFDI'],
  ['BCDEIJKL', 'EJBCIDLK'],
  ['BCDEHJKL', 'EJBCHDLK'],
  ['BCDEHIKL', 'EIBCHDLK'],
  ['BCDEHIJL', 'EJBCHDLI'],
  ['BCDEHIJK', 'EJBCHDIK'],
  ['BCDEGJKL', 'EGBCJDLK'],
  ['BCDEGIKL', 'EGBCIDLK'],
  ['BCDEGIJL', 'EGBCJDLI'],
  ['BCDEGIJK', 'EGBCJDIK'],
  ['BCDEGHKL', 'EGBCHDLK'],
  ['BCDEGHJL', 'HGBCJDLE'],
  ['BCDEGHJK', 'HGBCJDEK'],
  ['BCDEGHIL', 'EGBCHDLI'],
  ['BCDEGHIK', 'EGBCHDIK'],
  ['BCDEGHIJ', 'HGBCJDEI'],
  ['BCDEFJKL', 'CJBDEFLK'],
  ['BCDEFIKL', 'CEBDIFLK'],
  ['BCDEFIJL', 'CJBDEFLI'],
  ['BCDEFIJK', 'CJBDEFIK'],
  ['BCDEFHKL', 'CEBDHFLK'],
  ['BCDEFHJL', 'CJBDHFLE'],
  ['BCDEFHJK', 'CJBDHFEK'],
  ['BCDEFHIL', 'CEBDHFLI'],
  ['BCDEFHIK', 'CEBDHFIK'],
  ['BCDEFHIJ', 'CJBDHFEI'],
  ['BCDEFGKL', 'CGBDEFLK'],
  ['BCDEFGJL', 'CGBDJFLE'],
  ['BCDEFGJK', 'CGBDJFEK'],
  ['BCDEFGIL', 'CGBDEFLI'],
  ['BCDEFGIK', 'CGBDEFIK'],
  ['BCDEFGIJ', 'CGBDJFEI'],
  ['BCDEFGHL', 'CGBDHFLE'],
  ['BCDEFGHK', 'CGBDHFEK'],
  ['BCDEFGHJ', 'HGBCJFDE'],
  ['BCDEFGHI', 'CGBDHFEI'],
  ['AFGHIJKL', 'HJIFAGLK'],
  ['AEGHIJKL', 'EJIAHGLK'],
  ['AEFHIJKL', 'EJIFAHLK'],
  ['AEFGIJKL', 'EJIFAGLK'],
  ['AEFGHJKL', 'EGJFAHLK'],
  ['AEFGHIKL', 'EGIFAHLK'],
  ['AEFGHIJL', 'EGJFAHLI'],
  ['AEFGHIJK', 'EGJFAHIK'],
  ['ADGHIJKL', 'HJIDAGLK'],
  ['ADFHIJKL', 'HJIDAFLK'],
  ['ADFGIJKL', 'IGJDAFLK'],
  ['ADFGHJKL', 'HGJDAFLK'],
  ['ADFGHIKL', 'HGIDAFLK'],
  ['ADFGHIJL', 'HGJDAFLI'],
  ['ADFGHIJK', 'HGJDAFIK'],
  ['ADEHIJKL', 'EJIDAHLK'],
  ['ADEGIJKL', 'EJIDAGLK'],
  ['ADEGHJKL', 'EGJDAHLK'],
  ['ADEGHIKL', 'EGIDAHLK'],
  ['ADEGHIJL', 'EGJDAHLI'],
  ['ADEGHIJK', 'EGJDAHIK'],
  ['ADEFIJKL', 'EJIDAFLK'],
  ['ADEFHJKL', 'HJEDAFLK'],
  ['ADEFHIKL', 'HEIDAFLK'],
  ['ADEFHIJL', 'HJEDAFLI'],
  ['ADEFHIJK', 'HJEDAFIK'],
  ['ADEFGJKL', 'EGJDAFLK'],
  ['ADEFGIKL', 'EGIDAFLK'],
  ['ADEFGIJL', 'EGJDAFLI'],
  ['ADEFGIJK', 'EGJDAFIK'],
  ['ADEFGHKL', 'HGEDAFLK'],
  ['ADEFGHJL', 'HGJDAFLE'],
  ['ADEFGHJK', 'HGJDAFEK'],
  ['ADEFGHIL', 'HGEDAFLI'],
  ['ADEFGHIK', 'HGEDAFIK'],
  ['ADEFGHIJ', 'HGJDAFEI'],
  ['ACGHIJKL', 'HJICAGLK'],
  ['ACFHIJKL', 'HJICAFLK'],
  ['ACFGIJKL', 'IGJCAFLK'],
  ['ACFGHJKL', 'HGJCAFLK'],
  ['ACFGHIKL', 'HGICAFLK'],
  ['ACFGHIJL', 'HGJCAFLI'],
  ['ACFGHIJK', 'HGJCAFIK'],
  ['ACEHIJKL', 'EJICAHLK'],
  ['ACEGIJKL', 'EJICAGLK'],
  ['ACEGHJKL', 'EGJCAHLK'],
  ['ACEGHIKL', 'EGICAHLK'],
  ['ACEGHIJL', 'EGJCAHLI'],
  ['ACEGHIJK', 'EGJCAHIK'],
  ['ACEFIJKL', 'EJICAFLK'],
  ['ACEFHJKL', 'HJECAFLK'],
  ['ACEFHIKL', 'HEICAFLK'],
  ['ACEFHIJL', 'HJECAFLI'],
  ['ACEFHIJK', 'HJECAFIK'],
  ['ACEFGJKL', 'EGJCAFLK'],
  ['ACEFGIKL', 'EGICAFLK'],
  ['ACEFGIJL', 'EGJCAFLI'],
  ['ACEFGIJK', 'EGJCAFIK'],
  ['ACEFGHKL', 'HGECAFLK'],
  ['ACEFGHJL', 'HGJCAFLE'],
  ['ACEFGHJK', 'HGJCAFEK'],
  ['ACEFGHIL', 'HGECAFLI'],
  ['ACEFGHIK', 'HGECAFIK'],
  ['ACEFGHIJ', 'HGJCAFEI'],
  ['ACDHIJKL', 'HJICADLK'],
  ['ACDGIJKL', 'IGJCADLK'],
  ['ACDGHJKL', 'HGJCADLK'],
  ['ACDGHIKL', 'HGICADLK'],
  ['ACDGHIJL', 'HGJCADLI'],
  ['ACDGHIJK', 'HGJCADIK'],
  ['ACDFIJKL', 'CJIDAFLK'],
  ['ACDFHJKL', 'HJFCADLK'],
  ['ACDFHIKL', 'HFICADLK'],
  ['ACDFHIJL', 'HJFCADLI'],
  ['ACDFHIJK', 'HJFCADIK'],
  ['ACDFGJKL', 'CGJDAFLK'],
  ['ACDFGIKL', 'CGIDAFLK'],
  ['ACDFGIJL', 'CGJDAFLI'],
  ['ACDFGIJK', 'CGJDAFIK'],
  ['ACDFGHKL', 'HGFCADLK'],
  ['ACDFGHJL', 'CGJDAFLH'],
  ['ACDFGHJK', 'HGJCAFDK'],
  ['ACDFGHIL', 'HGFCADLI'],
  ['ACDFGHIK', 'HGFCADIK'],
  ['ACDFGHIJ', 'HGJCAFDI'],
  ['ACDEIJKL', 'EJICADLK'],
  ['ACDEHJKL', 'HJECADLK'],
  ['ACDEHIKL', 'HEICADLK'],
  ['ACDEHIJL', 'HJECADLI'],
  ['ACDEHIJK', 'HJECADIK'],
  ['ACDEGJKL', 'EGJCADLK'],
  ['ACDEGIKL', 'EGICADLK'],
  ['ACDEGIJL', 'EGJCADLI'],
  ['ACDEGIJK', 'EGJCADIK'],
  ['ACDEGHKL', 'HGECADLK'],
  ['ACDEGHJL', 'HGJCADLE'],
  ['ACDEGHJK', 'HGJCADEK'],
  ['ACDEGHIL', 'HGECADLI'],
  ['ACDEGHIK', 'HGECADIK'],
  ['ACDEGHIJ', 'HGJCADEI'],
  ['ACDEFJKL', 'CJEDAFLK'],
  ['ACDEFIKL', 'CEIDAFLK'],
  ['ACDEFIJL', 'CJEDAFLI'],
  ['ACDEFIJK', 'CJEDAFIK'],
  ['ACDEFHKL', 'HEFCADLK'],
  ['ACDEFHJL', 'HJFCADLE'],
  ['ACDEFHJK', 'HJECAFDK'],
  ['ACDEFHIL', 'HEFCADLI'],
  ['ACDEFHIK', 'HEFCADIK'],
  ['ACDEFHIJ', 'HJECAFDI'],
  ['ACDEFGKL', 'CGEDAFLK'],
  ['ACDEFGJL', 'CGJDAFLE'],
  ['ACDEFGJK', 'CGJDAFEK'],
  ['ACDEFGIL', 'CGEDAFLI'],
  ['ACDEFGIK', 'CGEDAFIK'],
  ['ACDEFGIJ', 'CGJDAFEI'],
  ['ACDEFGHL', 'HGFCADLE'],
  ['ACDEFGHK', 'HGECAFDK'],
  ['ACDEFGHJ', 'HGJCAFDE'],
  ['ACDEFGHI', 'HGECAFDI'],
  ['ABGHIJKL', 'HJBAIGLK'],
  ['ABFHIJKL', 'HJBAIFLK'],
  ['ABFGIJKL', 'IJBFAGLK'],
  ['ABFGHJKL', 'HJBFAGLK'],
  ['ABFGHIKL', 'HGBAIFLK'],
  ['ABFGHIJL', 'HJBFAGLI'],
  ['ABFGHIJK', 'HJBFAGIK'],
  ['ABEHIJKL', 'EJBAIHLK'],
  ['ABEGIJKL', 'EJBAIGLK'],
  ['ABEGHJKL', 'EJBAHGLK'],
  ['ABEGHIKL', 'EGBAIHLK'],
  ['ABEGHIJL', 'EJBAHGLI'],
  ['ABEGHIJK', 'EJBAHGIK'],
  ['ABEFIJKL', 'EJBAIFLK'],
  ['ABEFHJKL', 'EJBFAHLK'],
  ['ABEFHIKL', 'EIBFAHLK'],
  ['ABEFHIJL', 'EJBFAHLI'],
  ['ABEFHIJK', 'EJBFAHIK'],
  ['ABEFGJKL', 'EJBFAGLK'],
  ['ABEFGIKL', 'EGBAIFLK'],
  ['ABEFGIJL', 'EJBFAGLI'],
  ['ABEFGIJK', 'EJBFAGIK'],
  ['ABEFGHKL', 'EGBFAHLK'],
  ['ABEFGHJL', 'HJBFAGLE'],
  ['ABEFGHJK', 'HJBFAGEK'],
  ['ABEFGHIL', 'EGBFAHLI'],
  ['ABEFGHIK', 'EGBFAHIK'],
  ['ABEFGHIJ', 'HJBFAGEI'],
  ['ABDHIJKL', 'IJBDAHLK'],
  ['ABDGIJKL', 'IJBDAGLK'],
  ['ABDGHJKL', 'HJBDAGLK'],
  ['ABDGHIKL', 'IGBDAHLK'],
  ['ABDGHIJL', 'HJBDAGLI'],
  ['ABDGHIJK', 'HJBDAGIK'],
  ['ABDFIJKL', 'IJBDAFLK'],
  ['ABDFHJKL', 'HJBDAFLK'],
  ['ABDFHIKL', 'HIBDAFLK'],
  ['ABDFHIJL', 'HJBDAFLI'],
  ['ABDFHIJK', 'HJBDAFIK'],
  ['ABDFGJKL', 'FJBDAGLK'],
  ['ABDFGIKL', 'IGBDAFLK'],
  ['ABDFGIJL', 'FJBDAGLI'],
  ['ABDFGIJK', 'FJBDAGIK'],
  ['ABDFGHKL', 'HGBDAFLK'],
  ['ABDFGHJL', 'HGBDAFLJ'],
  ['ABDFGHJK', 'HGBDAFJK'],
  ['ABDFGHIL', 'HGBDAFLI'],
  ['ABDFGHIK', 'HGBDAFIK'],
  ['ABDFGHIJ', 'HGBDAFIJ'],
  ['ABDEIJKL', 'EJBAIDLK'],
  ['ABDEHJKL', 'EJBDAHLK'],
  ['ABDEHIKL', 'EIBDAHLK'],
  ['ABDEHIJL', 'EJBDAHLI'],
  ['ABDEHIJK', 'EJBDAHIK'],
  ['ABDEGJKL', 'EJBDAGLK'],
  ['ABDEGIKL', 'EGBAIDLK'],
  ['ABDEGIJL', 'EJBDAGLI'],
  ['ABDEGIJK', 'EJBDAGIK'],
  ['ABDEGHKL', 'EGBDAHLK'],
  ['ABDEGHJL', 'HJBDAGLE'],
  ['ABDEGHJK', 'HJBDAGEK'],
  ['ABDEGHIL', 'EGBDAHLI'],
  ['ABDEGHIK', 'EGBDAHIK'],
  ['ABDEGHIJ', 'HJBDAGEI'],
  ['ABDEFJKL', 'EJBDAFLK'],
  ['ABDEFIKL', 'EIBDAFLK'],
  ['ABDEFIJL', 'EJBDAFLI'],
  ['ABDEFIJK', 'EJBDAFIK'],
  ['ABDEFHKL', 'HEBDAFLK'],
  ['ABDEFHJL', 'HJBDAFLE'],
  ['ABDEFHJK', 'HJBDAFEK'],
  ['ABDEFHIL', 'HEBDAFLI'],
  ['ABDEFHIK', 'HEBDAFIK'],
  ['ABDEFHIJ', 'HJBDAFEI'],
  ['ABDEFGKL', 'EGBDAFLK'],
  ['ABDEFGJL', 'EGBDAFLJ'],
  ['ABDEFGJK', 'EGBDAFJK'],
  ['ABDEFGIL', 'EGBDAFLI'],
  ['ABDEFGIK', 'EGBDAFIK'],
  ['ABDEFGIJ', 'EGBDAFIJ'],
  ['ABDEFGHL', 'HGBDAFLE'],
  ['ABDEFGHK', 'HGBDAFEK'],
  ['ABDEFGHJ', 'HGBDAFEJ'],
  ['ABDEFGHI', 'HGBDAFEI'],
  ['ABCHIJKL', 'IJBCAHLK'],
  ['ABCGIJKL', 'IJBCAGLK'],
  ['ABCGHJKL', 'HJBCAGLK'],
  ['ABCGHIKL', 'IGBCAHLK'],
  ['ABCGHIJL', 'HJBCAGLI'],
  ['ABCGHIJK', 'HJBCAGIK'],
  ['ABCFIJKL', 'IJBCAFLK'],
  ['ABCFHJKL', 'HJBCAFLK'],
  ['ABCFHIKL', 'HIBCAFLK'],
  ['ABCFHIJL', 'HJBCAFLI'],
  ['ABCFHIJK', 'HJBCAFIK'],
  ['ABCFGJKL', 'CJBFAGLK'],
  ['ABCFGIKL', 'IGBCAFLK'],
  ['ABCFGIJL', 'CJBFAGLI'],
  ['ABCFGIJK', 'CJBFAGIK'],
  ['ABCFGHKL', 'HGBCAFLK'],
  ['ABCFGHJL', 'HGBCAFLJ'],
  ['ABCFGHJK', 'HGBCAFJK'],
  ['ABCFGHIL', 'HGBCAFLI'],
  ['ABCFGHIK', 'HGBCAFIK'],
  ['ABCFGHIJ', 'HGBCAFIJ'],
  ['ABCEIJKL', 'EJBAICLK'],
  ['ABCEHJKL', 'EJBCAHLK'],
  ['ABCEHIKL', 'EIBCAHLK'],
  ['ABCEHIJL', 'EJBCAHLI'],
  ['ABCEHIJK', 'EJBCAHIK'],
  ['ABCEGJKL', 'EJBCAGLK'],
  ['ABCEGIKL', 'EGBAICLK'],
  ['ABCEGIJL', 'EJBCAGLI'],
  ['ABCEGIJK', 'EJBCAGIK'],
  ['ABCEGHKL', 'EGBCAHLK'],
  ['ABCEGHJL', 'HJBCAGLE'],
  ['ABCEGHJK', 'HJBCAGEK'],
  ['ABCEGHIL', 'EGBCAHLI'],
  ['ABCEGHIK', 'EGBCAHIK'],
  ['ABCEGHIJ', 'HJBCAGEI'],
  ['ABCEFJKL', 'EJBCAFLK'],
  ['ABCEFIKL', 'EIBCAFLK'],
  ['ABCEFIJL', 'EJBCAFLI'],
  ['ABCEFIJK', 'EJBCAFIK'],
  ['ABCEFHKL', 'HEBCAFLK'],
  ['ABCEFHJL', 'HJBCAFLE'],
  ['ABCEFHJK', 'HJBCAFEK'],
  ['ABCEFHIL', 'HEBCAFLI'],
  ['ABCEFHIK', 'HEBCAFIK'],
  ['ABCEFHIJ', 'HJBCAFEI'],
  ['ABCEFGKL', 'EGBCAFLK'],
  ['ABCEFGJL', 'EGBCAFLJ'],
  ['ABCEFGJK', 'EGBCAFJK'],
  ['ABCEFGIL', 'EGBCAFLI'],
  ['ABCEFGIK', 'EGBCAFIK'],
  ['ABCEFGIJ', 'EGBCAFIJ'],
  ['ABCEFGHL', 'HGBCAFLE'],
  ['ABCEFGHK', 'HGBCAFEK'],
  ['ABCEFGHJ', 'HGBCAFEJ'],
  ['ABCEFGHI', 'HGBCAFEI'],
  ['ABCDIJKL', 'IJBCADLK'],
  ['ABCDHJKL', 'HJBCADLK'],
  ['ABCDHIKL', 'HIBCADLK'],
  ['ABCDHIJL', 'HJBCADLI'],
  ['ABCDHIJK', 'HJBCADIK'],
  ['ABCDGJKL', 'CJBDAGLK'],
  ['ABCDGIKL', 'IGBCADLK'],
  ['ABCDGIJL', 'CJBDAGLI'],
  ['ABCDGIJK', 'CJBDAGIK'],
  ['ABCDGHKL', 'HGBCADLK'],
  ['ABCDGHJL', 'HGBCADLJ'],
  ['ABCDGHJK', 'HGBCADJK'],
  ['ABCDGHIL', 'HGBCADLI'],
  ['ABCDGHIK', 'HGBCADIK'],
  ['ABCDGHIJ', 'HGBCADIJ'],
  ['ABCDFJKL', 'CJBDAFLK'],
  ['ABCDFIKL', 'CIBDAFLK'],
  ['ABCDFIJL', 'CJBDAFLI'],
  ['ABCDFIJK', 'CJBDAFIK'],
  ['ABCDFHKL', 'HFBCADLK'],
  ['ABCDFHJL', 'CJBDAFLH'],
  ['ABCDFHJK', 'HJBCAFDK'],
  ['ABCDFHIL', 'HFBCADLI'],
  ['ABCDFHIK', 'HFBCADIK'],
  ['ABCDFHIJ', 'HJBCAFDI'],
  ['ABCDFGKL', 'CGBDAFLK'],
  ['ABCDFGJL', 'CGBDAFLJ'],
  ['ABCDFGJK', 'CGBDAFJK'],
  ['ABCDFGIL', 'CGBDAFLI'],
  ['ABCDFGIK', 'CGBDAFIK'],
  ['ABCDFGIJ', 'CGBDAFIJ'],
  ['ABCDFGHL', 'CGBDAFLH'],
  ['ABCDFGHK', 'HGBCAFDK'],
  ['ABCDFGHJ', 'HGBCAFDJ'],
  ['ABCDFGHI', 'HGBCAFDI'],
  ['ABCDEJKL', 'EJBCADLK'],
  ['ABCDEIKL', 'EIBCADLK'],
  ['ABCDEIJL', 'EJBCADLI'],
  ['ABCDEIJK', 'EJBCADIK'],
  ['ABCDEHKL', 'HEBCADLK'],
  ['ABCDEHJL', 'HJBCADLE'],
  ['ABCDEHJK', 'HJBCADEK'],
  ['ABCDEHIL', 'HEBCADLI'],
  ['ABCDEHIK', 'HEBCADIK'],
  ['ABCDEHIJ', 'HJBCADEI'],
  ['ABCDEGKL', 'EGBCADLK'],
  ['ABCDEGJL', 'EGBCADLJ'],
  ['ABCDEGJK', 'EGBCADJK'],
  ['ABCDEGIL', 'EGBCADLI'],
  ['ABCDEGIK', 'EGBCADIK'],
  ['ABCDEGIJ', 'EGBCADIJ'],
  ['ABCDEGHL', 'HGBCADLE'],
  ['ABCDEGHK', 'HGBCADEK'],
  ['ABCDEGHJ', 'HGBCADEJ'],
  ['ABCDEGHI', 'HGBCADEI'],
  ['ABCDEFKL', 'CEBDAFLK'],
  ['ABCDEFJL', 'CJBDAFLE'],
  ['ABCDEFJK', 'CJBDAFEK'],
  ['ABCDEFIL', 'CEBDAFLI'],
  ['ABCDEFIK', 'CEBDAFIK'],
  ['ABCDEFIJ', 'CJBDAFEI'],
  ['ABCDEFHL', 'HFBCADLE'],
  ['ABCDEFHK', 'HEBCAFDK'],
  ['ABCDEFHJ', 'HJBCAFDE'],
  ['ABCDEFHI', 'HEBCAFDI'],
  ['ABCDEFGL', 'CGBDAFLE'],
  ['ABCDEFGK', 'CGBDAFEK'],
  ['ABCDEFGJ', 'CGBDAFEJ'],
  ['ABCDEFGI', 'CGBDAFEI'],
  ['ABCDEFGH', 'HGBCAFDE'],
];

/** 通過8グループ(昇順文字列) → 割当8文字 の高速引きマップ。 */
const ALLOCATION_BY_QUALIFIED: ReadonlyMap<string, string> = new Map(
  THIRD_PLACE_ALLOCATIONS.map(([qualified, assign]) => [qualified, assign]),
);

/** 入力を昇順・重複排除した正規化キー（A〜L 以外は無視）。 */
function normalizeGroupsKey(groups: readonly string[]): string {
  const set = new Set<string>();
  for (const g of groups) {
    const up = g.trim().toUpperCase();
    if (/^[A-L]$/.test(up)) set.add(up);
  }
  return [...set].sort().join('');
}

export type ThirdPlaceAssignment = {
  /** ホスト試合ID（Round of 32）。 */
  matchId: number;
  /** その試合でグループ1位の相手になるグループ（=ホスト）。 */
  host: GroupLetter;
  /** 割り当てられた3位通過グループ。 */
  thirdPlaceGroup: GroupLetter;
};

/**
 * 「Round of 32 に進む8グループ（＝ベスト3位を出した8グループ）」を渡すと、
 * 各ホスト試合に入る3位グループを FIFA 公式割当どおりに返す純関数。
 *
 * @param qualifiedThirdGroups 3位が通過した8グループ（順不同・大文字小文字不問）。
 * @returns ホスト試合×割当グループの配列（THIRD_PLACE_HOST_MATCHES と同じ試合順）。
 *          入力がちょうど8グループでない／表に存在しない組合せなら `null`。
 */
export function assignThirdPlaceSlots(
  qualifiedThirdGroups: readonly string[],
): ThirdPlaceAssignment[] | null {
  const key = normalizeGroupsKey(qualifiedThirdGroups);
  if (key.length !== 8) return null;

  const assign = ALLOCATION_BY_QUALIFIED.get(key);
  if (!assign) return null;

  // 割当8文字は ALLOCATION_HOST_ORDER 順。ホスト → 3位グループ の引きを作る。
  const byHost = new Map<GroupLetter, GroupLetter>();
  ALLOCATION_HOST_ORDER.forEach((host, idx) => {
    byHost.set(host, assign[idx] as GroupLetter);
  });

  return THIRD_PLACE_HOST_MATCHES.map(({ matchId, host }) => ({
    matchId,
    host,
    thirdPlaceGroup: byHost.get(host)!,
  }));
}
